import { Label, GitHubRepo, Repos } from '../types';

/**
 * 生成 JSON 数据
 */
export const generateJson = (
  stars: GitHubRepo[],
  labels: Label[],
  repos: Repos
): string => {
  const data = {
    version: '1.0',
    lastUpdate: new Date().toISOString(),
    totalCount: stars.length,
    labels,
    repos,
    stars: stars.map(star => ({
      id: star.id,
      name: star.name,
      full_name: star.full_name,
      description: star.description,
      html_url: star.html_url,
      stargazers_count: star.stargazers_count,
      language: star.language,
      updated_at: star.updated_at,
      owner: {
        login: star.owner.login,
        avatar_url: star.owner.avatar_url,
      },
    })),
  };

  return JSON.stringify(data, null, 2);
};

/**
 * 生成 README Markdown 内容
 */
export const generateReadme = (
  stars: GitHubRepo[],
  labels: Label[],
  repos: Repos
): string => {
  const lines: string[] = [];
  
  lines.push('# My GitHub Stars');
  lines.push('');
  lines.push(`> 最后更新: ${new Date().toLocaleString('zh-CN')}`);
  lines.push(`> 共 ${stars.length} 个项目`);
  lines.push('');
  
  // 按标签分组
  const labelGroups: { [labelId: string]: GitHubRepo[] } = {};
  const unlabeledRepos: GitHubRepo[] = [];
  
  stars.forEach(star => {
    const repoInfo = repos[star.full_name];
    const customLabels = repoInfo?.customLabels || [];
    const generatedLabels = repoInfo?.generatedLabels || [];
    const repoLabelIds = [...customLabels, ...generatedLabels];

    if (repoLabelIds.length === 0) {
      unlabeledRepos.push(star);
    } else {
      repoLabelIds.forEach((labelId: string) => {
        if (!labelGroups[labelId]) {
          labelGroups[labelId] = [];
        }
        labelGroups[labelId].push(star);
      });
    }
  });
  
  // 输出标签分类
  lines.push('## 标签分类');
  lines.push('');
  
  labels.forEach(label => {
    const labelRepos = labelGroups[label.id] || [];  // 修改变量名，避免冲突
    if (labelRepos.length > 0) {
      lines.push(`### ${label.name} (${labelRepos.length})`);
      lines.push('');
      
      // 按星标数排序
      labelRepos.sort((a, b) => b.stargazers_count - a.stargazers_count);
      
      labelRepos.forEach(repo => {
        const starCount = formatStarCount(repo.stargazers_count);
        const remark = repos[repo.full_name]?.remark;  // 使用原始 repos 参数
        lines.push(`- [${repo.full_name}](${repo.html_url}) ⭐ ${starCount}`);
        if (repo.description) {
          lines.push(`  ${repo.description}`);
        }
        if (remark) {
          lines.push(`  > ${remark}`);
        }
      });
      lines.push('');
    }
  });
  
  // 未分类项目
  if (unlabeledRepos.length > 0) {
    lines.push('### 未分类');
    lines.push('');
    unlabeledRepos.forEach(repo => {
      const starCount = formatStarCount(repo.stargazers_count);
      const remark = repos[repo.full_name]?.remark;  // 使用原始 repos 参数
      lines.push(`- [${repo.full_name}](${repo.html_url}) ⭐ ${starCount}`);
      if (repo.description) {
        lines.push(`  ${repo.description}`);
      }
      if (remark) {
        lines.push(`  > ${remark}`);
      }
    });
    lines.push('');
  }
  
  // 所有项目列表（按星标数排序）
  lines.push('## 所有项目');
  lines.push('');
  lines.push('按星标数排序：');
  lines.push('');
  
  const sortedStars = [...stars].sort((a, b) => b.stargazers_count - a.stargazers_count);
  
  sortedStars.forEach((repo: GitHubRepo) => {
    const starCount = formatStarCount(repo.stargazers_count);
    const repoInfo = repos[repo.full_name];
    const customLabels = repoInfo?.customLabels || [];
    const generatedLabels = repoInfo?.generatedLabels || [];
    const labelIds = [...customLabels, ...generatedLabels];
    const labelNames = labelIds
      .map(id => labels.find(l => l.id === id)?.name)
      .filter(Boolean)
      .join(', ');
    const remark = repos[repo.full_name]?.remark;  // 使用原始 repos 参数
    
    lines.push(`- [${repo.full_name}](${repo.html_url}) ⭐ ${starCount}${labelNames ? ` [${labelNames}]` : ''}`);
    if (repo.description) {
      lines.push(`  ${repo.description}`);
    }
    if (remark) {
      lines.push(`  > ${remark}`);
    }
  });
  
  lines.push('');
  lines.push('---');
  lines.push('*Generated by [GitHub Star Manager](https://github.com/your-username/star-manager)*');
  
  return lines.join('\n');
};

/**
 * 格式化星标数
 */
const formatStarCount = (count: number): string => {
  if (count >= 1000) {
    return `${(count / 1000).toFixed(1)}K`;
  }
  return count.toString();
};
